import './globals.css';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import GoogleProvider from "./GoogleProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GoogleProvider>{children}</GoogleProvider>
      </body>
    </html>
  );
}
